spring.application.name=hrManagement

# Swagger Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.disable-swagger-default-url=true

# Enable/Disable Swagger UI in production
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true